
menu:
  Archives: 
    link: /archives/
    icon: archive.svg
  Resume: 
    link: /resume/
    icon: resume.svg
  Projects: 
    link: /categories/projects/
    icon: projects.svg
  Notes: 
    link: /categories/notes/
    icon: notes.svg
  Fun: 
    link: /categories/fun/
    icon: fun.svg